### ISSUE TITLE
Saving after optimization not working

### ISSUE THREAD

**Issue by fdonnet** [charlyie/resmushit-cli#6]
Hello,

It's very strange. I run the command and Î have this output : 
[2020-12-30 17:51:04] File optimized by 72% (from 1.74MB to 506.30KB). Retrieving...
[2020-12-30 17:51:04] File saved as ./xxxx-optimized.png
[2020-12-30 17:51:04] Optimization completed

But no xxxx-optimized.png exists at the end in the folder or via a find command from the root folder of the system. It seems that something doesn't allow the saving process without any additionnal info.

Thx for this tool ;)

**Comment by fdonnet** [comment]
Forget that it s working just now... maybe I sent to much file for a first testing and the api was not happy about that. Thx a lot.

**Comment by fdonnet** [comment]
Wihtout curl quiet : 

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Tried with -k or --insecure in the curl command and it seems to solve the issue... weird... maybe something to correct on the api side....

**Comment by charlyie** [comment]
Hi @fdonnet

Sorry for this late reply. This point has been fixed on both sides :)
Please update your cli tool using --update command, to fetch the version 1.1.1.

Best regards,
Charles
