### ISSUE TITLE
wpcli support?

### ISSUE THREAD

**Issue by bajpangosh** [charlyie/resmushit-cli#7]
is it support wp cli?

**Comment by charlyie** [comment]
Hi @bajpangosh 

No it's totally another CLI plugin, but we'll think about a WP-CLI plugin 👍 

Cheers,
Charles

**Comment by charlyie** [comment]
Hi @bajpangosh 

We've heard your request, and added to the last Wordpress plugin version, a WP-CLI support! We'll enhance it with more features in future releases, but it should be a good start for you.

Do not hesitate to send us your feedback :)

Cheers,
Charles

**Comment by bajpangosh** [comment]
![image](https://user-images.githubusercontent.com/10659120/117673674-9bc6ba80-b1c8-11eb-89ac-5a2de24efb4c.png)

Thank You! it's so fast, we recommending your wordpress plugin in our wordpress stack script. 
[High Traffic wordpress server configuration](https://github.com/bajpangosh/High-Traffic-wordpress-server-configuration)
